version: '3'
services:
  dev:
    image: node:13
    volumes: 
      - nodemodules:/app/node_modules
      - .:/app
    working_dir: /app
    command: npm run dev
    ports:
      - 5000:5000
      - 35729:35729

volumes:
  nodemodules:
    external: true